name: Run every 10 minute

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  cron:
    name: Run every 10 minutes
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world"
