name: Secrets workflows

on:
  pull_request:
    branches: [ "main" ]

env: 
  API_SCPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "the value of ${{ secrets.SECRET_API_KEY }} is $API_SCPROJ_PATH"